//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeLens.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EyeLens.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information and application source code go to {0}..
        /// </summary>
        public static string AboutPage_ProjectRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_ProjectRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeLens {0}.
        /// </summary>
        public static string AboutPage_VersionRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_VersionRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageButtonText {
            get {
                return ResourceManager.GetString("AboutPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeLens.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeLens.
        /// </summary>
        public static string ApplicationTitle1 {
            get {
                return ResourceManager.GetString("ApplicationTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color picker.
        /// </summary>
        public static string ColorPickerButtonText {
            get {
                return ResourceManager.GetString("ColorPickerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antique.
        /// </summary>
        public static string Filter_Antique {
            get {
                return ResourceManager.GetString("Filter_Antique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Enhance.
        /// </summary>
        public static string Filter_AutoEnhance {
            get {
                return ResourceManager.GetString("Filter_AutoEnhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartoon.
        /// </summary>
        public static string Filter_Cartoon {
            get {
                return ResourceManager.GetString("Filter_Cartoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse Weighted Grayscale.
        /// </summary>
        public static string Filter_Custom {
            get {
                return ResourceManager.GetString("Filter_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grayscale.
        /// </summary>
        public static string Filter_Grayscale {
            get {
                return ResourceManager.GetString("Filter_Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Pen.
        /// </summary>
        public static string Filter_MagicPen {
            get {
                return ResourceManager.GetString("Filter_MagicPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Filter_None {
            get {
                return ResourceManager.GetString("Filter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posterize.
        /// </summary>
        public static string Filter_Posterize {
            get {
                return ResourceManager.GetString("Filter_Posterize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpness.
        /// </summary>
        public static string Filter_Sharpness {
            get {
                return ResourceManager.GetString("Filter_Sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamp.
        /// </summary>
        public static string Filter_Stamp {
            get {
                return ResourceManager.GetString("Filter_Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///\&quot;FF0000\&quot;:\&quot;Red\&quot;,
        ///\&quot;00FF00\&quot;:\&quot;Green\&quot;,
        ///\&quot;0000FF\&quot;:\&quot;Blue\&quot;,
        ///}.
        /// </summary>
        public static string jsonColorData {
            get {
                return ResourceManager.GetString("jsonColorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ruColorNames.json.
        /// </summary>
        public static string JsonColorFile {
            get {
                return ResourceManager.GetString("JsonColorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FPS.
        /// </summary>
        public static string MainPage_FrameRateTextBlock_Format {
            get {
                return ResourceManager.GetString("MainPage_FrameRateTextBlock_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting camera....
        /// </summary>
        public static string MainPage_StatusTextBlock_StartingCamera {
            get {
                return ResourceManager.GetString("MainPage_StatusTextBlock_StartingCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to focusing.
        /// </summary>
        public static string MakingFocus {
            get {
                return ResourceManager.GetString("MakingFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next filter.
        /// </summary>
        public static string NextEffectButtonText {
            get {
                return ResourceManager.GetString("NextEffectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous filter.
        /// </summary>
        public static string PreviousEffectButtonText {
            get {
                return ResourceManager.GetString("PreviousEffectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageButtonText {
            get {
                return ResourceManager.GetString("SettingsPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak actions in app.
        /// </summary>
        public static string SpeechInterfaceCheckbox {
            get {
                return ResourceManager.GetString("SpeechInterfaceCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string ZoomInButtonText {
            get {
                return ResourceManager.GetString("ZoomInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zooming in.
        /// </summary>
        public static string ZoomingIn {
            get {
                return ResourceManager.GetString("ZoomingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zooming out.
        /// </summary>
        public static string ZoomingOut {
            get {
                return ResourceManager.GetString("ZoomingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string ZoomOutButtonText {
            get {
                return ResourceManager.GetString("ZoomOutButtonText", resourceCulture);
            }
        }
    }
}
