//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeLens.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EyeLens.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Nokia example application demonstrating the real-time use of effects provided by the Nokia Imaging SDK. The effects are applies to the stream of images received from the camera device..
        /// </summary>
        public static string AboutPage_AboutRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_AboutRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.github.com/nokia-developer/real-time-filter-demo/.
        /// </summary>
        public static string AboutPage_Hyperlink_Project {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information and application source code go to {0}..
        /// </summary>
        public static string AboutPage_ProjectRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_ProjectRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeLens {0}.
        /// </summary>
        public static string AboutPage_VersionRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_VersionRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageButtonText {
            get {
                return ResourceManager.GetString("AboutPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeLens.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeLens.
        /// </summary>
        public static string ApplicationTitle1 {
            get {
                return ResourceManager.GetString("ApplicationTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to винтажный.
        /// </summary>
        public static string Filter_Antique {
            get {
                return ResourceManager.GetString("Filter_Antique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to автонастройка.
        /// </summary>
        public static string Filter_AutoEnhance {
            get {
                return ResourceManager.GetString("Filter_AutoEnhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to анимационный.
        /// </summary>
        public static string Filter_Cartoon {
            get {
                return ResourceManager.GetString("Filter_Cartoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвертированный черно-белый.
        /// </summary>
        public static string Filter_Custom {
            get {
                return ResourceManager.GetString("Filter_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черно-белый.
        /// </summary>
        public static string Filter_Grayscale {
            get {
                return ResourceManager.GetString("Filter_Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to волшебное перо.
        /// </summary>
        public static string Filter_MagicPen {
            get {
                return ResourceManager.GetString("Filter_MagicPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не указан.
        /// </summary>
        public static string Filter_None {
            get {
                return ResourceManager.GetString("Filter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to резкость.
        /// </summary>
        public static string Filter_Sharpness {
            get {
                return ResourceManager.GetString("Filter_Sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оттиск.
        /// </summary>
        public static string Filter_Stamp {
            get {
                return ResourceManager.GetString("Filter_Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FPS.
        /// </summary>
        public static string MainPage_FrameRateTextBlock_Format {
            get {
                return ResourceManager.GetString("MainPage_FrameRateTextBlock_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускаем камеру....
        /// </summary>
        public static string MainPage_StatusTextBlock_StartingCamera {
            get {
                return ResourceManager.GetString("MainPage_StatusTextBlock_StartingCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фокусировка.
        /// </summary>
        public static string MakingFocus {
            get {
                return ResourceManager.GetString("MakingFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующий фильтр.
        /// </summary>
        public static string NextEffectButtonText {
            get {
                return ResourceManager.GetString("NextEffectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий фильтр.
        /// </summary>
        public static string PreviousEffectButtonText {
            get {
                return ResourceManager.GetString("PreviousEffectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru-RU.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string SettingsPageButtonText {
            get {
                return ResourceManager.GetString("SettingsPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приблизить.
        /// </summary>
        public static string ZoomInButtonText {
            get {
                return ResourceManager.GetString("ZoomInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приближение.
        /// </summary>
        public static string ZoomingIn {
            get {
                return ResourceManager.GetString("ZoomingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдаление.
        /// </summary>
        public static string ZoomingOut {
            get {
                return ResourceManager.GetString("ZoomingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдалить.
        /// </summary>
        public static string ZoomOutButtonText {
            get {
                return ResourceManager.GetString("ZoomOutButtonText", resourceCulture);
            }
        }
    }
}
