//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34003
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeLens.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EyeLens.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is a Nokia example application demonstrating the real-time use of effects provided by the Nokia Imaging SDK. The effects are applies to the stream of images received from the camera device..
        /// </summary>
        public static string AboutPage_AboutRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_AboutRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://www.github.com/nokia-developer/real-time-filter-demo/.
        /// </summary>
        public static string AboutPage_Hyperlink_Project {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For more information and application source code go to {0}..
        /// </summary>
        public static string AboutPage_ProjectRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_ProjectRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EyeLens {0}.
        /// </summary>
        public static string AboutPage_VersionRun_Text {
            get {
                return ResourceManager.GetString("AboutPage_VersionRun_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на about.
        /// </summary>
        public static string AboutPageButtonText {
            get {
                return ResourceManager.GetString("AboutPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EyeLens.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EyeLens.
        /// </summary>
        public static string ApplicationTitle1 {
            get {
                return ResourceManager.GetString("ApplicationTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на винтажный.
        /// </summary>
        public static string Filter_Antique {
            get {
                return ResourceManager.GetString("Filter_Antique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на автонастройка.
        /// </summary>
        public static string Filter_AutoEnhance {
            get {
                return ResourceManager.GetString("Filter_AutoEnhance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на анимационный.
        /// </summary>
        public static string Filter_Cartoon {
            get {
                return ResourceManager.GetString("Filter_Cartoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инвертированный черно-белый.
        /// </summary>
        public static string Filter_Custom {
            get {
                return ResourceManager.GetString("Filter_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Черно-белый.
        /// </summary>
        public static string Filter_Grayscale {
            get {
                return ResourceManager.GetString("Filter_Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на волшебное перо.
        /// </summary>
        public static string Filter_MagicPen {
            get {
                return ResourceManager.GetString("Filter_MagicPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не указан.
        /// </summary>
        public static string Filter_None {
            get {
                return ResourceManager.GetString("Filter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на постеризация.
        /// </summary>
        public static string Filter_Posterize {
            get {
                return ResourceManager.GetString("Filter_Posterize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на резкость.
        /// </summary>
        public static string Filter_Sharpness {
            get {
                return ResourceManager.GetString("Filter_Sharpness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оттиск.
        /// </summary>
        public static string Filter_Stamp {
            get {
                return ResourceManager.GetString("Filter_Stamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///\&quot;FF0000\&quot;:\&quot;Red\&quot;,
        ///\&quot;00FF00\&quot;:\&quot;Green\&quot;,
        ///\&quot;0000FF\&quot;:\&quot;Blue\&quot;,
        ///}.
        /// </summary>
        public static string jsonColorData {
            get {
                return ResourceManager.GetString("jsonColorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ruColorNames.json.
        /// </summary>
        public static string JsonColorFile {
            get {
                return ResourceManager.GetString("JsonColorFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} FPS.
        /// </summary>
        public static string MainPage_FrameRateTextBlock_Format {
            get {
                return ResourceManager.GetString("MainPage_FrameRateTextBlock_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запускаем камеру....
        /// </summary>
        public static string MainPage_StatusTextBlock_StartingCamera {
            get {
                return ResourceManager.GetString("MainPage_StatusTextBlock_StartingCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фокусировка.
        /// </summary>
        public static string MakingFocus {
            get {
                return ResourceManager.GetString("MakingFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующий фильтр.
        /// </summary>
        public static string NextEffectButtonText {
            get {
                return ResourceManager.GetString("NextEffectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предыдущий фильтр.
        /// </summary>
        public static string PreviousEffectButtonText {
            get {
                return ResourceManager.GetString("PreviousEffectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-RU.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        public static string SettingsPageButtonText {
            get {
                return ResourceManager.GetString("SettingsPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приблизить.
        /// </summary>
        public static string ZoomInButtonText {
            get {
                return ResourceManager.GetString("ZoomInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приближение.
        /// </summary>
        public static string ZoomingIn {
            get {
                return ResourceManager.GetString("ZoomingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отдаление.
        /// </summary>
        public static string ZoomingOut {
            get {
                return ResourceManager.GetString("ZoomingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отдалить.
        /// </summary>
        public static string ZoomOutButtonText {
            get {
                return ResourceManager.GetString("ZoomOutButtonText", resourceCulture);
            }
        }
    }
}
